#!/usr/bin/perl -w
use strict;
use warnings;

#--------------------------------------------------------------------------------------------------------------------
sub Usage{
	print "perl mergeOverlapPeaks.pl <consensusPeaks.mx> <minOverlap> <sumOverlap> <mergedPeaks>\n";
	print "\t<consensusPeaks.mx>\tconsensusPeaks.mx of all 16 samples, generated by \"bedtools unionbedg\"\n";
	print "\t<minOverlap>\tminimum overlap number of one peak WITHIN one group (4 samples/group; suggested 3)\n";
	print "\t<sumOverlap>\tTotal overlaps of one peak in ALL 16 samples (suggested 6)\n";
	print "\t<mergedPeaks>\toutput merged peaks\n\n";
	print "\tFunction: Merge overlapped peaks across all 16 samples\n";
	print "\tQirui Zhang (qirui.zhang\@med.lu.se)\n";
	print "\t19-02-2020\n\n";
}

#--------------------------------------------------------------------------------------------------------------------
my ($matrix, $minOverlap, $sumOverlap, $merged)=@ARGV;
if (@ARGV!=4){
	Usage;
	exit;
}

#--------------------------------------------------------------------------------------------------------------------
open (IN, "$matrix") or die "$!\n";
open (OUT, "> $merged") or die "$!\n";
my $i=1;
while (<IN>){
	chomp;
	my @tmp=(split/\s+/,$_);
	my $sum_grp1=$tmp[3]+$tmp[4]+$tmp[5]+$tmp[6];
	my $sum_grp2=$tmp[7]+$tmp[8]+$tmp[9]+$tmp[10];
	my $sum_grp3=$tmp[11]+$tmp[12]+$tmp[13]+$tmp[14];
	my $sum_grp4=$tmp[15]+$tmp[16]+$tmp[17]+$tmp[18];
	my $sum_all=$sum_grp1+$sum_grp2+$sum_grp3+$sum_grp4;

	if($sum_all>=$sumOverlap && ($sum_grp1>=$minOverlap || $sum_grp2>=$minOverlap || $sum_grp3>=$minOverlap || $sum_grp4>=$minOverlap)){
		print OUT "$tmp[0]\t$tmp[1]\t$tmp[2]\tpeak_$i\n";
		$i++;
	}
}
close IN;
close OUT;

